[package]
name = "myrustfmt"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
tracing-test = { version = "0.2.5", features = ["no-env-filter"] }
