// test-kind: no-change

fn test() {
    match x {
        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
            if CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC => {}
        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
            if CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC =>
        // hi
        {}
        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
            if CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC =>
        {/* yo */}
        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
            if CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC =>
        {
            x
        }
        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
            if CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC =>
        {
            let x;
            x
        }
    }
}
