// test-kind: no-change

fn test() {
    match x {
        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
            if CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC => {}
        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
            if CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC =>
        {/* yo */}
        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
            if CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC =>
        {
            x
        }
        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
            if CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC =>
        {
            let x;
            x
        }
    }
}
